### PR TITLE
API support for running starccm on scania infra

### PR DESCRIPTION
**Pull request by stephenkeefauver**
### Purpose
API needs to deploy to prod and support running starccm app on scania infrastructure 

#### Job Scripts:
- Accept the param-file from create-job-script in CLI 
- use the param-file to populate the template job script uploaded in create-application
- Application tar is accessed in memory from s3 and the .sh.j2 (jinja template) is downloaded to be populated based on param-file
- job_script_data_as_str field returns the rendered job-script populated based on param-file (screenshot attached for what CLI returns from this). 
image

#### Applications
- Accept tar from cli and upload to s3  -> functionality moved out of CLI

### CODE REVIEW

**Comment by stephenkeefauver** [comment]
Tested on Scania Infra running starccm example job submission. Ready for review and merge

**Comment by stephenkeefauver** [comment]
removed accountsRedis and optoutsRedis and deployed/tested api with those changes

**Comment by stephenkeefauver** [comment]
Merged - will branch off master for work on updates for legacy jobbergate starccm

**Comment by jamesbeedy** [comment]
+1

**Pull request merged**
